services:
  mongo:
    container_name: my-app-db
    image: mongo:latest
    restart: unless-stopped
    env_file: .env.development
    ports:
      - "27017:27017"
  api:
    container_name: api
    build: ./api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./api:/user/src/app
